# Generated by Django 5.1.6 on 2025-02-20 12:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('bachelor', 'Bachelor'), ('master', 'Master')], default='bachelor', max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('contract_amount', models.BigIntegerField()),
                ('donated_amount', models.BigIntegerField(default=0)),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='shared.university')),
            ],
            options={
                'db_table': 'students',
            },
        ),
    ]
