# Generated by Django 5.1.6 on 2025-02-20 12:33

import apps.shared.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'New'), ('moderation', 'Moderation'), ('approved', 'Approved'), ('canceled', 'Canceled')], default='new', max_length=10)),
                ('sponsor_type', models.CharField(choices=[('legal', 'Legal'), ('individual', 'Individual')], default='individual', max_length=10)),
                ('sponsor_name', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=20, unique=True, validators=[apps.shared.validators.validate_phone_number])),
                ('payment_amount', models.BigIntegerField(blank=True)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('comment', models.TextField(null=True)),
                ('is_approved', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'applications',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sponsor_type', models.CharField(choices=[('legal', 'Legal'), ('individual', 'Individual')], default='individual', max_length=10)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('organization', models.CharField(max_length=150, null=True)),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('card', 'Card'), ('transfer', 'Transfer')], default='cash', max_length=10)),
                ('balance', models.BigIntegerField()),
                ('phone_number', models.CharField(max_length=20, unique=True, validators=[apps.shared.validators.validate_phone_number])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
